"""Turn jinja_oracle.json (written by jinja_oracle.py) into src/jinja/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/jinja_oracle.py
    python3 examples/jinja_fixture.py
    tuo fmt src/jinja/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "jinja_oracle.json")))


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = jinja::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n"
    )


sources = sorted(data["sources"].items())
cases = data["cases"]
src = """// Generated by examples/jinja_fixture.py from jinja_oracle.json — do not
// edit by hand.
//
// The backend's 30 email templates as shipped, and 100 renders of them by
// Jinja2 3.1.6 through the backend's own email functions in English and
// Finnish: the template, the context Jinja2 was given (JSON; `safe` lists
// the dotted paths of the values that were `Markup`, one per line), and
// the output.

module jinja::fixture;

/// How many templates there are.
///
/// # Example
/// ```tuo
/// let n = jinja::fixture::source_count();
/// ```
pub fn source_count() -> Int {
    %d
}

""" % len(sources)
src += table("source_name", "The name of template `index`, as `{%% extends %%}` refers to it.", [lit(n) for n, _ in sources]) + "\n"
src += table("source", "The text of template `index`.", [lit(t) for _, t in sources]) + "\n"
src += (
    "/// How many renders there are.\n///\n/// # Example\n/// ```tuo\n"
    f"/// let n = jinja::fixture::count(); // {len(cases)}\n/// ```\n"
    f"pub fn count() -> Int {{\n    {len(cases)}\n}}\n\n"
)
src += table("name", "The name of render `index`.", [lit(c["name"]) for c in cases]) + "\n"
src += table("template", "The template render `index` used.", [lit(c["template"]) for c in cases]) + "\n"
src += table("context", "The context of render `index`, as JSON.", [lit(json.dumps(c["context"], separators=(",", ":"), ensure_ascii=False)) for c in cases]) + "\n"
src += table("safe", "The dotted paths of the `Markup` values in render `index`, one per line.", [lit("\n".join(c["safe"])) for c in cases]) + "\n"
src += table("output", "What Jinja2 rendered for `index`.", [lit(c["output"]) for c in cases])
open(os.path.join(here, "..", "src", "jinja", "fixture.tuo"), "w").write(src)
print(len(sources), "templates,", len(cases), "renders")
