"""Turn numpy_oracle.json (written by numpy_oracle.py) into src/numpy/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/numpy_oracle.py
    python3 examples/numpy_fixture.py
    tuo fmt src/numpy/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "numpy_oracle.json")))
cases = data["cases"]


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(name, doc, vals):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = numpy::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> Str {{\n{body}\n    \"\"\n}}\n\n"
    )


# Inputs shared between cases are written once.
inputs = []
seen = {}
refs = []
for c in cases:
    parts = []
    for name, text in c["inputs"]:
        if text not in seen:
            seen[text] = len(inputs)
            inputs.append(text)
        parts.append("%s=%d" % (name, seen[text]))
    refs.append(",".join(parts))

src = f"""// Generated by examples/numpy_fixture.py from numpy_oracle.json — do not
// edit by hand.
//
// {len(cases)} expressions evaluated by numpy {data['numpy']} (CPython {data['python']},
// {data['machine']}), each over a few named input arrays, and what numpy
// returned — `dtype|shape|elements`, floats as their IEEE bit patterns in
// hex and any NaN as `nan` — or raised, `Type: message`. The {len(inputs)}
// distinct inputs are written once, in the same form (NaNs as their bits);
// a case names its inputs as `a=3,b=4`.

module numpy::fixture;

/// How many cases there are.
///
/// # Example
/// ```tuo
/// let n = numpy::fixture::case_count();
/// ```
pub fn case_count() -> Int {{
    {len(cases)}
}}

"""
src += table("case_group", "The group case `index` belongs to.", [lit(c["group"]) for c in cases])
src += table("case_name", "What case `index` pins.", [lit(c["name"]) for c in cases])
src += table("case_inputs", "The inputs case `index` names, as `name=input,…`.", [lit(r) for r in refs])
src += table("case_expr", "The expression case `index` evaluates.", [lit(c["expr"]) for c in cases])
src += table("case_result", "What numpy made of case `index`.", [lit(c["result"]) for c in cases])
src += table("input_text", "Input array `index`, as `dtype|shape|elements`.", [lit(t) for t in inputs])

with open(os.path.join(here, "..", "src", "numpy", "fixture.tuo"), "w") as fh:
    fh.write(src.rstrip() + "\n")
print("%d cases, %d distinct inputs, %d bytes" % (len(cases), len(inputs), len(src)))
