"""Turn ratelimit_oracle.json (written by ratelimit_oracle.py) into
src/ratelimit/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/ratelimit_oracle.py
    python3 examples/ratelimit_fixture.py
    tuo fmt src/ratelimit/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "ratelimit_oracle.json")))
v = data["versions"]


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = ratelimit::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n\n"
    )


def constant(name, doc, value, ret="Int"):
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let n = ratelimit::fixture::{name}();\n/// ```\n"
        f"pub fn {name}() -> {ret} {{\n    {value}\n}}\n\n"
    )


def boolean(b):
    return "true" if b else "false"


# --- parse_many -------------------------------------------------------------

parse = data["parse"]


def items_text(p):
    if not p["ok"]:
        return ""
    return "\n".join(
        "|".join([str(i["amount"]), str(i["multiples"]), i["granularity"], i["repr"], str(i["expiry"]), i["key"]])
        for i in p["items"]
    )


# --- memory scripts, flattened ----------------------------------------------

mem = []
for n, script in enumerate(data["memory"]):
    for op in script["ops"]:
        mem.append((n, script["name"], op))


def result_text(op, r):
    if op in ("hit", "test", "check"):
        return boolean(r)
    if op == "stats":
        return f"{r[0]},{r[1]}"
    return ""


# --- redis calls ------------------------------------------------------------
#
# The first call is `check`, and redis-py opened its connection there with
# two `CLIENT SETINFO` commands of its own; they are redis-py's handshake,
# not limits', so they and their replies are dropped.

redis = []
for call in data["redis"]:
    cmds, replies = call["commands"], call["replies"]
    while cmds and cmds[0].startswith("*4\r\n$6\r\nCLIENT\r\n$7\r\nSETINFO\r\n"):
        cmds, replies = cmds[1:], replies[1:]
    redis.append({**call, "commands": cmds, "replies": replies})

LIMIT_TEXT = {"5 per 1 minute": "5/minute", "3 per 1 hour": "3/hour"}

# --- apps, flattened --------------------------------------------------------

reqs = []
for n, app in enumerate(data["apps"]):
    for case in app["cases"]:
        reqs.append((n, app["name"], case))


def headers_text(c):
    return "".join(f"{k}: {val}\n" for k, val in c["headers"])


src = f"""// Generated by examples/ratelimit_fixture.py from ratelimit_oracle.json —
// do not edit by hand.
//
// What limits {v['limits']} and slowapi {v['slowapi']} did, captured on CPython
// {v['python']} from the backend's virtualenv with `time.time` frozen:
//
// * `parse_*`: {len(parse)} strings handed to `limits.parse_many` — each item
//   as `amount|multiples|granularity|repr|expiry|key_for(ip, path)`, one
//   per line, or the `ValueError`.
// * `memory_*`: {len(mem)} calls on `FixedWindowRateLimiter(MemoryStorage())`,
//   {len(data['memory'])} scripts each on a fresh storage: the call, the time
//   in milliseconds, the limit string, the identifiers (one per line), the
//   cost, and what came back — `true`/`false`, or `reset_ms,remaining`.
// * `redis_*`: {len(redis)} calls on the same strategy over `RedisStorage`
//   (redis-py {v['redis-py']}, redis-server {v['redis-server']}), with every
//   command written and every reply read, back to back. redis-py's own
//   `CLIENT SETINFO` handshake is left out.
// * `app_*`: {len(reqs)} requests through slowapi in front of FastAPI, in
//   {len(data['apps'])} applications (`examples/ratelimit_oracle.py` has
//   them): the client address, method, path, and time; the status, body,
//   and rate-limit headers (`name: value` lines, repeated headers joined
//   with `, `); and `request.state.view_rate_limit` with its window stats.

module ratelimit::fixture;

"""

src += constant("t0", "The frozen clock's origin, in milliseconds since the epoch.", data["t0"])

src += constant("parse_count", "How many strings `parse_many` was given.", len(parse))
src += table("parse_text", "The string of parse case `index`.", [lit(p["text"]) for p in parse])
src += table("parse_ok", "Whether parse case `index` parsed.", [boolean(p["ok"]) for p in parse], "Bool", "false")
src += table("parse_items", "The items of parse case `index`, one per line.", [lit(items_text(p)) for p in parse])
src += table("parse_error", "The `ValueError` of parse case `index`, or empty.", [lit(p.get("error", "")) for p in parse])

src += constant("memory_count", "How many memory-storage calls there are, across all scripts.", len(mem))
src += table("memory_script", "Which script call `index` belongs to; each starts on a fresh storage.", [str(n) for n, _, _ in mem], "Int", "0 - 1")
src += table("memory_script_name", "The name of the script call `index` belongs to.", [lit(name) for _, name, _ in mem])
src += table("memory_op", "The call: `hit`, `test`, `stats`, or `clear`.", [lit(op["op"]) for _, _, op in mem])
src += table("memory_at", "The frozen time of call `index`, in milliseconds.", [str(op["at"]) for _, _, op in mem], "Int", "0")
src += table("memory_limit", "The limit string of call `index`.", [lit(op["limit"]) for _, _, op in mem])
src += table("memory_ids", "The identifiers of call `index`, one per line.", [lit("\n".join(op["ids"])) for _, _, op in mem])
src += table("memory_cost", "The cost of call `index`.", [str(op["cost"]) for _, _, op in mem], "Int", "0")
src += table("memory_result", "What call `index` returned.", [lit(result_text(op["op"], op["result"])) for _, _, op in mem])

src += constant("redis_count", "How many Redis-storage calls there are.", len(redis))
src += table("redis_op", "The call: `check`, `hit`, `test`, `stats`, or `clear`.", [lit(c["op"]) for c in redis])
src += table("redis_limit", "The limit string of call `index`, or empty.", [lit(LIMIT_TEXT.get(c["limit"], "")) for c in redis])
src += table("redis_ids", "The identifiers of call `index`, one per line.", [lit("\n".join(c["ids"] or [])) for c in redis])
src += table("redis_cost", "The cost of call `index`.", [str(c["cost"] or 0) for c in redis], "Int", "0")
src += table("redis_result", "What call `index` returned.", [lit(result_text(c["op"], c["result"])) for c in redis])
src += table("redis_commands", "The commands redis-py wrote for call `index`, back to back.", [lit("".join(c["commands"])) for c in redis])
src += table("redis_replies", "The replies redis-py read for call `index`, back to back.", [lit("".join(c["replies"])) for c in redis])

src += constant("app_count", "How many requests there are, across all applications.", len(reqs))
src += table("app_index", "Which application request `index` went to.", [str(n) for n, _, _ in reqs], "Int", "0 - 1")
src += table("app_name", "The name of that application.", [lit(name) for _, name, _ in reqs])
src += table("app_host", "The client address (empty: no client host).", [lit(c["host"]) for _, _, c in reqs])
src += table("app_method", "The method of request `index`.", [lit(c["method"]) for _, _, c in reqs])
src += table("app_path", "The path of request `index`.", [lit(c["path"]) for _, _, c in reqs])
src += table("app_at", "The frozen time of request `index`, in milliseconds.", [str(c["at"]) for _, _, c in reqs], "Int", "0")
src += table("app_status", "The status FastAPI answered.", [str(c["status"]) for _, _, c in reqs], "Int", "0")
src += table("app_body", "The body FastAPI answered.", [lit(c["body"]) for _, _, c in reqs])
src += table("app_headers", "The content type and rate-limit headers, as `name: value` lines.", [lit(headers_text(c)) for _, _, c in reqs])
src += table("app_has_view", "Whether `view_rate_limit` was set.", [boolean(c["view"] is not None) for _, _, c in reqs], "Bool", "false")
src += table("app_view_limit", "The `repr` of the view's limit, or empty.", [lit(c["view"]["limit"] if c["view"] else "") for _, _, c in reqs])
src += table("app_view_args", "The view's key arguments, one per line.", [lit("\n".join(c["view"]["args"]) if c["view"] else "") for _, _, c in reqs])
src += table("app_view_reset", "The view's window reset, in milliseconds.", [str(c["view"]["reset"] if c["view"] else 0) for _, _, c in reqs], "Int", "0")
src += table("app_view_remaining", "The view's remaining amount.", [str(c["view"]["remaining"] if c["view"] else 0) for _, _, c in reqs], "Int", "0")

open(os.path.join(here, "..", "src", "ratelimit", "fixture.tuo"), "w").write(src.rstrip("\n") + "\n")
print("parse", len(parse), "memory", len(mem), "redis", len(redis), "requests", len(reqs))
