"""Turn s3_oracle.json (written by s3_oracle.py) into src/s3/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/s3_oracle.py   # writes examples/s3_oracle.json
    python3 examples/s3_fixture.py                           # rewrites src/s3/fixture.tuo
    tuo fmt src/s3/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
cases = json.load(open(os.path.join(here, "s3_oracle.json")))


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = s3::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n"
    )


def lines(headers):
    return "".join(f"{k}: {v}\n" for k, v in sorted(headers.items()))


header = """// Generated by examples/s3_fixture.py from s3_oracle.json — do not edit
// by hand.
//
// What boto3 1.43.98 / botocore 1.43.98 put on the wire for the S3 calls
// the backend makes, with a frozen clock (20260922T083000Z) and the AWS
// documentation's example credentials, against an R2-shaped HTTPS
// endpoint and the docker compose MinIO over HTTP. A presigned URL is a
// case whose method is `URL`. Headers are `name: value` lines, sorted.

"""
src = header + "module s3::fixture;\n\n"
src += (
    "/// How many cases there are.\n///\n/// # Example\n/// ```tuo\n"
    f"/// let n = s3::fixture::count(); // {len(cases)}\n/// ```\n"
    f"pub fn count() -> Int {{\n    {len(cases)}\n}}\n\n"
)
src += table("name", "The name of case `index`.", [lit(c["name"]) for c in cases]) + "\n"
src += table("method", "The method of case `index`, or `URL` for a presigned URL.", [lit(c["method"]) for c in cases]) + "\n"
src += table("url", "The full URL of case `index`.", [lit(c["url"]) for c in cases]) + "\n"
src += table("headers", "The headers of case `index`, sorted, one per line.", [lit(lines(c["headers"])) for c in cases]) + "\n"
src += table("body", "The body of case `index`.", [lit(c["body"]) for c in cases])
open(os.path.join(here, "..", "src", "s3", "fixture.tuo"), "w").write(src)
print(len(cases), "cases")
