"""Turn sentry_oracle.json (written by sentry_oracle.py) into
src/log/fixture.tuo and src/sentry/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/sentry_oracle.py
    python3 examples/sentry_fixture.py
    tuo fmt src/log/fixture.tuo src/sentry/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "sentry_oracle.json")))


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(module, name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = {module}::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n"
    )


def count(module, n):
    return (
        "/// How many cases there are.\n///\n/// # Example\n/// ```tuo\n"
        f"/// let n = {module}::fixture::count(); // {n}\n/// ```\n"
        f"pub fn count() -> Int {{\n    {n}\n}}\n\n"
    )


lines = data["lines"]
src = """// Generated by examples/sentry_fixture.py from sentry_oracle.json — do not
// edit by hand.
//
// What CPython 3.14's `logging` formats, for records with a fixed time
// (2026-09-22 08:30:00.123 UTC), in the two formats app/main.py
// configures: the development one and the production JSON one. `args`
// are the record's arguments, one per line.

module log::fixture;

""" + count("log", len(lines))
src += table("log", "name", "The name of case `index`.", [lit(c["name"]) for c in lines]) + "\n"
src += table("log", "logger", "The logger name of case `index`.", [lit(c["logger"]) for c in lines]) + "\n"
src += table("log", "level", "The numeric level of case `index`.", [str(c["level"]) for c in lines], "Int", "0") + "\n"
src += table("log", "template", "The message template of case `index`.", [lit(c["template"]) for c in lines]) + "\n"
src += table("log", "args", "The arguments of case `index`, as a JSON array.", [lit(c["args"]) for c in lines]) + "\n"
src += table("log", "message", "The formatted message of case `index`.", [lit(c["message"]) for c in lines]) + "\n"
src += table("log", "plain", "The development-format line of case `index`.", [lit(c["plain"]) for c in lines]) + "\n"
src += table("log", "json", "The production-format line of case `index`, as the backend's format string writes it — unescaped.", [lit(c["json"]) for c in lines])
os.makedirs(os.path.join(here, "..", "src", "log"), exist_ok=True)
open(os.path.join(here, "..", "src", "log", "fixture.tuo"), "w").write(src)

envs = data["envelopes"]
src = """// Generated by examples/sentry_fixture.py from sentry_oracle.json — do not
// edit by hand.
//
// The envelopes sentry-sdk 2.69.2 serialized for a fixed sequence of
// calls (see examples/sentry_oracle.py), with what is Python's rather
// than the protocol's stripped and every id and timestamp fixed. Each is
// the whole envelope: header line, item header, payload, newline.

module sentry::fixture;

""" + count("sentry", len(envs))
src += table("sentry", "name", "The name of case `index`.", [lit(c["name"]) for c in envs]) + "\n"
src += table("sentry", "envelope", "The envelope of case `index`.", [lit(c["envelope"]) for c in envs]) + "\n"
src += f"/// The `X-Sentry-Auth` header sentry-sdk sends.\n///\n/// # Example\n/// ```tuo\n/// let a = sentry::fixture::auth();\n/// ```\npub fn auth() -> Str {{\n    {lit(data['auth'])}\n}}\n"
os.makedirs(os.path.join(here, "..", "src", "sentry"), exist_ok=True)
open(os.path.join(here, "..", "src", "sentry", "fixture.tuo"), "w").write(src)
print(len(lines), "lines,", len(envs), "envelopes")
