"""Turn settings_oracle.json (written by settings_oracle.py) into
src/dotenv/fixture.tuo and src/settings/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/settings_oracle.py
    python3 examples/settings_fixture.py
    tuo fmt src/dotenv/fixture.tuo src/settings/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "settings_oracle.json")))


def dumps(value):
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(module, name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = {module}::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n"
    )


def constant(module, name, doc, value, ret="Int"):
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let n = {module}::fixture::{name}();\n/// ```\n"
        f"pub fn {name}() -> {ret} {{\n    {value}\n}}\n"
    )


# --- dotenv -----------------------------------------------------------------

cases = data["dotenv"]
env_lines = "".join(f"{k}={v}\n" for k, v in data["expand_env"])
src = """// Generated by examples/settings_fixture.py from settings_oracle.json — do
// not edit by hand.
//
// %d `.env` texts and what python-dotenv 1.2.3 made of them: the items of
// `dotenv_values` as JSON `[key, value]` pairs (a bare key's value is
// null), expanded against the environment `expand_env` gives, and the
// lines it warned it could not parse, comma-separated. The last three are
// the backend's tracked `.env.*.example` files.

module dotenv::fixture;

""" % len(cases)
src += constant("dotenv", "expand_env", "The environment `${…}` was expanded against, as `NAME=value` lines.", lit(env_lines), "Str") + "\n"
src += constant("dotenv", "count", "How many texts there are.", len(cases)) + "\n"
src += table("dotenv", "name", "The name of case `index`.", [lit(c["name"]) for c in cases]) + "\n"
src += table("dotenv", "text", "The `.env` text of case `index`.", [lit(c["text"]) for c in cases]) + "\n"
src += table("dotenv", "values", "`dotenv_values` of case `index`, as JSON pairs.", [lit(dumps(c["values"])) for c in cases]) + "\n"
src += table("dotenv", "error_lines", "The lines python-dotenv warned about in case `index`.", [lit(",".join(str(n) for n in c["errors"])) for c in cases])
open(os.path.join(here, "..", "src", "dotenv", "fixture.tuo"), "w").write(src)

# --- settings ---------------------------------------------------------------

fields = data["fields"]
cases = data["settings"]
src = """// Generated by examples/settings_fixture.py from settings_oracle.json — do
// not edit by hand.
//
// The backend's `Settings` declaration as `model_fields` gives it — %d
// fields with their kinds, defaults (JSON), and validation aliases (one per
// line) — and %d instantiations of it by pydantic-settings 2.15.0 on
// Pydantic 2.13.5, each with a whole process environment (JSON pairs) and,
// when `has_dotenv`, a `.env` file: the outcome (`ok`, `invalid`, `error`)
// and the output — `model_dump(mode="json")`, the validation errors as
// FastAPI renders them, or the `SettingsError` message.

module settings::fixture;

""" % (len(fields), len(cases))
src += constant("settings", "field_count", "How many fields `Settings` declares.", len(fields)) + "\n"
src += table("settings", "field_name", "The name of field `index`.", [lit(f["name"]) for f in fields]) + "\n"
src += table("settings", "field_kind", "The kind of field `index`: `str`, `int`, `float`, `bool`, `list_str`, `list_int`.", [lit(f["kind"]) for f in fields]) + "\n"
src += table("settings", "field_optional", "Whether field `index` is `Optional`.", ["true" if f["optional"] else "false" for f in fields], "Bool", "false") + "\n"
src += table("settings", "field_default", "The default of field `index`, as JSON.", [lit(f["default"]) for f in fields]) + "\n"
src += table("settings", "field_aliases", "The validation aliases of field `index`, one per line.", [lit("\n".join(f["aliases"])) for f in fields]) + "\n"
src += constant("settings", "count", "How many instantiations there are.", len(cases)) + "\n"
src += table("settings", "name", "The name of case `index`.", [lit(c["name"]) for c in cases]) + "\n"
src += table("settings", "env", "The whole environment of case `index`, as JSON pairs.", [lit(dumps(c["env"])) for c in cases]) + "\n"
src += table("settings", "has_dotenv", "Whether case `index` had a `.env` file.", ["false" if c["dotenv"] is None else "true" for c in cases], "Bool", "false") + "\n"
src += table("settings", "dotenv", "The `.env` text of case `index`.", [lit(c["dotenv"] or "") for c in cases]) + "\n"
src += table("settings", "outcome", "`ok`, `invalid`, or `error`.", [lit(c["outcome"]) for c in cases]) + "\n"
src += table("settings", "output", "What pydantic-settings produced for case `index`.", [lit(c["output"]) for c in cases])
open(os.path.join(here, "..", "src", "settings", "fixture.tuo"), "w").write(src)
print(len(data["dotenv"]), "dotenv cases,", len(fields), "fields,", len(cases), "settings cases")
