"""Turn zip_oracle.json (written by zip_oracle.py) into src/inflate/fixture.tuo,
the large streams under examples/zip-test/inflate/, and src/zip/fixture.tuo.

    ../shallowflaws/.venv/bin/python examples/zip_oracle.py
    python3 examples/zip_fixture.py
    tuo fmt src/inflate/fixture.tuo src/zip/fixture.tuo
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(here, "zip_oracle.json")))
INLINE = 8192


def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif o < 32 or o > 126:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def table(module, name, doc, vals, ret="Str", default='""'):
    body = "\n".join(
        f"    if index == {i} {{\n        return {v};\n    }}" for i, v in enumerate(vals)
    )
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let v = {module}::fixture::{name}(0);\n/// ```\n"
        f"pub fn {name}(take index: Int) -> {ret} {{\n{body}\n    {default}\n}}\n\n"
    )


def constant(module, name, doc, value, ret="Int"):
    return (
        f"/// {doc}\n///\n/// # Example\n/// ```tuo\n/// let n = {module}::fixture::{name}();\n/// ```\n"
        f"pub fn {name}() -> {ret} {{\n    {value}\n}}\n\n"
    )


def boolean(b):
    return "true" if b else "false"


# --- inflate ----------------------------------------------------------------

cases = data["inflate"]
big_dir = os.path.join(here, "zip-test", "inflate")
os.makedirs(big_dir, exist_ok=True)
for f in os.listdir(big_dir):
    os.remove(os.path.join(big_dir, f))
files = []
for c in cases:
    raw = bytes.fromhex(c["input"])
    if len(raw) > INLINE:
        path = f"examples/zip-test/inflate/{c['name']}.bin"
        open(os.path.join(here, "..", path), "wb").write(raw)
        files.append(path)
    else:
        files.append("")

src = f"""// Generated by examples/zip_fixture.py from zip_oracle.json — do not
// edit by hand.
//
// {len(cases)} deflate streams and what `zlib.decompress` (zlib {data['zlib']},
// CPython {data['python']}) made of them: streams zlib compressed at every
// level and strategy, streams written bit by bit, and malformed ones. Each
// has its `wbits` (-15 raw, 15 zlib-wrapped, 9 a small zlib window), its
// bytes as hex — or, past {INLINE} bytes, the path of a file holding them,
// which only native code can read — and either the output's length,
// CRC-32, and (up to 512 bytes) hex, or the `zlib.error` message.

module inflate::fixture;

"""
m = "inflate"
src += constant(m, "count", "How many streams there are.", len(cases))
src += table(m, "name", "The name of stream `index`.", [lit(c["name"]) for c in cases])
src += table(m, "wbits", "The `wbits` it was decompressed with.", [str(c["wbits"]) for c in cases], "Int", "0")
src += table(m, "input_hex", "Its bytes as hex, or empty when they are in `input_file`.",
             [lit(c["input"] if not f else "") for c, f in zip(cases, files)])
src += table(m, "input_file", "The file holding its bytes, or empty.", [lit(f) for f in files])
src += table(m, "ok", "Whether it decompressed.", [boolean(c["ok"]) for c in cases], "Bool", "false")
src += table(m, "length", "The output's length.", [str(c.get("length", 0)) for c in cases], "Int", "0")
src += table(m, "crc", "The output's CRC-32.", [str(c.get("crc", 0)) for c in cases], "Int", "0")
src += table(m, "output_hex", "The output as hex, when at most 512 bytes.", [lit(c.get("output", "")) for c in cases])
src += table(m, "error", "The `zlib.error` message, or empty.", [lit(c.get("error", "")) for c in cases])
open(os.path.join(here, "..", "src", "inflate", "fixture.tuo"), "w").write(src.rstrip("\n") + "\n")
print("inflate", len(cases), "streams,", sum(1 for f in files if f), "in files")


# --- zip --------------------------------------------------------------------

zips = data["zip"]
entries = [(k, e) for k, z in enumerate(zips) for e in z.get("entries", [])]
reads = [(k, r) for k, z in enumerate(zips) for r in z.get("reads", [])]


def wide(v):
    """zip::archive holds 64-bit fields saturated: 2^60 from there to 2^63,
    2^60 + 1 beyond (see `zip::archive::wide`)."""
    if v >= 1 << 63:
        return (1 << 60) + 1
    return min(v, 1 << 60)


def entry_fields(e):
    return "|".join(str(v) for v in [e["compress_type"], e["flag_bits"], e["crc"], wide(e["compress_size"]),
                                        wide(e["file_size"]), wide(e["header_offset"]), ",".join(str(x) for x in e["date_time"]), e["comment"],
                                        e["extra_len"], "dir" if e["is_dir"] else "file"])


src = f"""// Generated by examples/zip_fixture.py from zip_oracle.json — do not
// edit by hand.
//
// {len(zips)} archives opened by `zipfile.ZipFile` (CPython {data['python']}) from a file
// on disk: their bytes as hex; whether they opened, and the exception
// (type and message) when not; the archive comment; every entry of
// `infolist()` — `filename`, `orig_filename`, and
// `compress_type|flag_bits|CRC|compress_size|file_size|header_offset|
// date_time|comment hex|len(extra)|dir or file`, the sizes and offset
// saturated as `zip::archive::wide` holds them; and `zf.read(name)` of
// every distinct name and of one that is not there: the data's length,
// CRC-32, and (up to 256 bytes) hex, or the exception.

module zip::fixture;

"""
m = "zip"
src += constant(m, "archive_count", "How many archives there are.", len(zips))
src += table(m, "archive_name", "The name of archive `index`.", [lit(z["name"]) for z in zips])
src += table(m, "archive_hex", "The bytes of archive `index`, as hex.", [lit(z["bytes"]) for z in zips])
src += table(m, "archive_ok", "Whether `ZipFile` opened it.", [boolean(z["ok"]) for z in zips], "Bool", "false")
src += table(m, "archive_error_type", "The exception's type when it did not.", [lit(z["error"]["type"] if not z["ok"] else "") for z in zips])
src += table(m, "archive_error", "The exception's message when it did not.", [lit(z["error"]["message"] if not z["ok"] else "") for z in zips])
src += table(m, "archive_comment_hex", "The archive comment, as hex.", [lit(z.get("comment", "")) for z in zips])
src += constant(m, "entry_count", "How many entries there are, across all archives.", len(entries))
src += table(m, "entry_archive", "The archive entry `index` belongs to.", [str(k) for k, _ in entries], "Int", "0 - 1")
src += table(m, "entry_filename", "Its `filename`.", [lit(e["filename"]) for _, e in entries])
src += table(m, "entry_orig_filename", "Its `orig_filename`.", [lit(e["orig_filename"]) for _, e in entries])
src += table(m, "entry_fields", "Its other fields, `|`-separated.", [lit(entry_fields(e)) for _, e in entries])
src += constant(m, "read_count", "How many reads there are, across all archives.", len(reads))
src += table(m, "read_archive", "The archive read `index` was of.", [str(k) for k, _ in reads], "Int", "0 - 1")
src += table(m, "read_name", "The name read.", [lit(r["name"]) for _, r in reads])
src += table(m, "read_ok", "Whether the read returned data.", [boolean(r["ok"]) for _, r in reads], "Bool", "false")
src += table(m, "read_length", "The data's length.", [str(r.get("length", 0)) for _, r in reads], "Int", "0")
src += table(m, "read_crc", "The data's CRC-32.", [str(r.get("crc", 0)) for _, r in reads], "Int", "0")
src += table(m, "read_data_hex", "The data as hex, when at most 256 bytes.", [lit(r.get("data", "")) for _, r in reads])
src += table(m, "read_error_type", "The exception's type, or empty.", [lit(r["error"]["type"] if not r["ok"] else "") for _, r in reads])
src += table(m, "read_error", "The exception's message, or empty.", [lit(r["error"]["message"] if not r["ok"] else "") for _, r in reads])
os.makedirs(os.path.join(here, "..", "src", "zip"), exist_ok=True)
open(os.path.join(here, "..", "src", "zip", "fixture.tuo"), "w").write(src.rstrip("\n") + "\n")
print("zip", len(zips), "archives,", len(entries), "entries,", len(reads), "reads")
